[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Smart Contract Security Checklist"
authors = [{name = "engn33r", email = "engn33r@yacademy.dev"}]
dynamic = ["version", "description"]
